# Generated by Django 4.0.3 on 2023-07-19 15:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('username', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=50)),
                ('dob', models.DateField(null=True)),
                ('gender', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=500, null=True)),
                ('city', models.CharField(max_length=50)),
                ('postcode', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=500)),
                ('ac_type', models.CharField(max_length=50)),
                ('card_number', models.IntegerField(default=8050504020303020)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Creditdebit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('bankName', models.CharField(max_length=50)),
                ('accountNumber', models.CharField(max_length=50)),
                ('cardType', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Insurance_Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=50)),
                ('dateOfBirth', models.DateField()),
                ('contactNumber', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('bankName', models.CharField(max_length=50)),
                ('accountNumber', models.CharField(max_length=50)),
                ('insuranceType', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Loan_Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('loanamount', models.CharField(max_length=50)),
                ('ssn', models.CharField(max_length=50)),
                ('monthlyincome', models.CharField(max_length=50)),
                ('bankaccount', models.CharField(max_length=50)),
                ('loantype', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=100, max_digits=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateTimeField()),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient_transactions', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
